/**
 * Effect types, default parameters, and per-type configs for the pixy.js shader API.
 * Derived from mebiusbox's pixy.js (MIT) — https://github.com/mebiusbox/pixy.js
 */

export const EFFECT_TYPES = [
	"Wood", "Circle", "Solar", "Corona", "Spark", "Ring", "Gradation", "GradationLine",
	"Flash", "Cone", "Flower", "FlowerFun", "WaveRing", "Smoke", "Flame", "FlameEye",
	"Fire", "Cell", "Lightning", "Flare", "Flare2", "Flare3", "LensFlare", "Sun",
	"MagicCircle", "Mandara", "Explosion", "Explosion2", "Cross", "Laser", "Laser2",
	"Light", "Cloud", "Cloud2", "CoherentNoise", "PerlinNoise", "SeamlessNoise",
	"BooleanNoise", "CellNoise", "TurbulentNoise", "FbmNoise", "FbmNoise2", "FbmNoise3",
	"RandomNoise", "VoronoiNoise", "SparkNoise", "MarbleNoise", "TessNoise", "GradientNoise",
	"Checker", "FlameLance", "Bonfire", "Snow", "DiamondGear", "BrushStroke", "Speckle",
	"Bubbles", "Pentagon", "Grunge", "Energy", "InkSplat", "Particle", "Electric",
	"Caustics", "Squiggles", "WaterTurbulence", "Trabeculum", "BinaryMatrix"
];

export function getDefaultEffectController() {
	return {
		animate: false,
		time: 0,
		resolution: "512",
		polarConversion: false,
		cHeightScale: 2,
		normalMap: false,
		tiling: false,
		cRadialMask: 1,
		cColorBalanceShadowsR: 0, cColorBalanceShadowsG: 0, cColorBalanceShadowsB: 0,
		cColorBalanceMidtonesR: 0, cColorBalanceMidtonesG: 0, cColorBalanceMidtonesB: 0,
		cColorBalanceHighlightsR: 0, cColorBalanceHighlightsG: 0, cColorBalanceHighlightsB: 0,
		type: "Wood"
	};
}

export function getDefaultEffectParameters() {
	return {
		cFrequency: 30, cAmplitude: 0.01, cIntensity: 0.5,
		cDirectionX: 0, cDirectionY: 1, cPowerExponent: 1,
		cRadius: 0.5, cInnerRadius: 1, cInnerRadius2: 1,
		cSize: 1, cWidth: 1, cHeight: 1, cDepth: 1, cColor: 1,
		cPetals: 6, cOffset: 0.2, cVolume: 3, cBeta: 4, cDelta: 0.05,
		cScale: 1, cInnerWidth: 0.4, cStrength: 1, cPower: 1, cRange: 2,
		cEmission: 1, cBloom: 1,
		cLightX: 1, cLightY: 1, cLightZ: 1, cAmbient: 1,
		cSmoothness: 1, cSmoothnessPower: 1, cThickness: 1, cThicknessPower: 1,
		cCameraTilt: 0, cCameraPan: 0, cSpeed: 1, cAngle: 0,
		cDensity: 1, cAlpha: 1, cRepeat: 1, cScaleShift: 0,
		cBias: 0, cGain: 0, cInvert: 0, cThreshold: 0,
		cDiamondGearTeeth: 18, cDiamondGearMid: 0.8,
		cBrushStrokeX1: -0.4, cBrushStrokeY1: 0,
		cBrushStrokeX2: 1.1, cBrushStrokeY2: 0.8,
		cBubblesVariation: 1,
		cFlameEyeInnerFade: 1, cFlameEyeOuterFade: 1, cFlameEyeBorder: 1,
		cSplatLines: 20, cSplatSpotStep: 0.04,
		cTrabeculumVariation: 2,
		cLifeTime: 0.9, cGravity: 0.26, cCount: 300,
		cToonEnable: false, cToonDark: 0.8, cToonLight: 0.95,
		cExplosionRadius: 1.75, cExplosionDownScale: 1.25, cExplosionGrain: 2,
		cExplosionSpeed: 0.3, cExplosionBallness: 2, cExplosionGrowth: 2.2,
		cExplosionFade: 1.6, cExplosionDensity: 1.35, cExplosionContrast: 1,
		cExplosionRollingInitDamp: 0.3, cExplosionRollingSpeed: 2,
		cExplosionDelayRange: 0.25, cExplosionBallSpread: 1,
		cExplosionBloom: 0, cExplosionEmission: 0.2, cExplosionColor: 1,
		cNoiseOctave: 8, cNoiseFrequency: 1, cNoiseAmplitude: 0.65,
		cNoisePersistence: 0.5, cNoiseScale: 1,
		cNoiseSphereEnable: false, cNoiseGraphEnable: false,
		cNoiseStrength: 1, cNoiseDepth: 3, cNoiseSize: 8, cNoiseLacunarity: 2,
		cTurbulence: 0, cRidge: 0, cRidgeOffset: 0.9,
		cGradientNoise: 0, cValueNoise: 0, cVoronoiNoise: 0, cVoronoiCell: 0, cSimplexNoise: 1
	};
}

/**
 * Per-type parameter lists: which parameters each effect type uses.
 */
export const EFFECT_PARAMETERS = {
	Wood: ["cFrequency", "cPowerExponent"],
	Circle: ["cRadius", "cPowerExponent"],
	Solar: ["cIntensity", "cPowerExponent"],
	Spark: ["cIntensity", "cPowerExponent"],
	Ring: ["cRadius", "cWidth", "cPowerExponent"],
	Gradation: ["cDirectionX", "cDirectionY", "cPowerExponent"],
	GradationLine: ["cDirectionX", "cDirectionY", "cOffset", "cPowerExponent"],
	Flash: ["cFrequency", "cPowerExponent"],
	Cone: ["cDirectionX", "cDirectionY", "cPowerExponent"],
	Flower: ["cPetals", "cRadius", "cIntensity", "cPowerExponent"],
	FlowerFun: ["cPetals", "cRadius", "cOffset", "cIntensity", "cPowerExponent"],
	WaveRing: ["cRadius", "cWidth", "cFrequency", "cAmplitude", "cPowerExponent"],
	Flame: ["cIntensity", "cWidth", "cScale"],
	FlameEye: ["cSpeed", "cFlameEyeInnerFade", "cFlameEyeOuterFade", "cFlameEyeBorder", "cColor"],
	Cell: ["cIntensity", "cPowerExponent", "cSize"],
	Smoke: ["cVolume", "cBeta", "cDelta"],
	Lightning: ["cIntensity", "cFrequency", "cWidth"],
	Flare: ["cIntensity", "cPowerExponent"],
	Flare2: ["cIntensity", "cPowerExponent"],
	Flare3: ["cIntensity", "cPowerExponent"],
	MagicCircle: [],
	Mandara: ["cRadius", "cInnerRadius", "cInnerRadius2"],
	Cross: ["cIntensity", "cPowerExponent"],
	Explosion: ["cCameraTilt", "cCameraPan", "cExplosionRadius", "cExplosionDownScale", "cExplosionGrain", "cExplosionSpeed", "cExplosionBallness", "cExplosionGrowth", "cExplosionFade", "cExplosionDensity", "cExplosionContrast", "cExplosionRollingInitDamp", "cExplosionRollingSpeed", "cExplosionDelayRange", "cExplosionBallSpread"],
	Explosion2: ["cCameraPan", "cExplosionSpeed", "cExplosionDensity", "cEmission", "cBloom", "cColor"],
	Corona: ["cIntensity", "cRadius", "cSize"],
	Fire: ["cIntensity", "cStrength", "cPower", "cRange", "cWidth", "cColor"],
	LensFlare: ["cRadius", "cRange", "cColor", "cPowerExponent"],
	Sun: ["cRadius", "cColor"],
	Laser: ["cWidth", "cColor"],
	Laser2: ["cWidth", "cInnerWidth"],
	Light: ["cRadius", "cPowerExponent", "cColor"],
	Cloud: ["cWidth", "cHeight", "cDepth", "cIntensity", "cLightX", "cLightY", "cLightZ", "cAmbient", "cSmoothness", "cSmoothnessPower", "cThickness", "cThicknessPower", "cCameraTilt", "cCameraPan"],
	Cloud2: ["cIntensity", "cDensity", "cThickness", "cColor"],
	CoherentNoise: ["cNoiseOctave", "cNoiseFrequency", "cNoiseAmplitude", "cNoiseLacunarity", "cNoisePersistence", "cGradientNoise", "cValueNoise", "cVoronoiNoise", "cVoronoiCell", "cSimplexNoise", "cRepeat", "cTurbulence", "cRidge", "cRidgeOffset", "cScaleShift", "cPowerExponent", "cBias", "cGain", "cThreshold", "cInvert", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	PerlinNoise: ["cNoiseOctave", "cNoisePersistence", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	SeamlessNoise: ["cNoiseOctave", "cNoisePersistence", "cNoiseScale", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	BooleanNoise: ["cNoiseFrequency", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	CellNoise: ["cNoiseFrequency", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	RandomNoise: ["cNoiseFrequency", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	FbmNoise: ["cNoiseOctave", "cNoiseAmplitude", "cNoiseFrequency", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	FbmNoise2: ["cNoiseOctave", "cNoiseAmplitude", "cNoiseFrequency", "cScale", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	FbmNoise3: ["cNoiseOctave", "cNoiseAmplitude", "cNoiseFrequency", "cNoiseScale", "cOffset", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	TurbulentNoise: ["cNoiseOctave", "cNoiseAmplitude", "cNoiseFrequency", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	SparkNoise: ["cNoiseFrequency", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	VoronoiNoise: ["cNoiseFrequency", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	MarbleNoise: ["cScale", "cFrequency", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	TessNoise: ["cNoiseFrequency", "cOffset", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	GradientNoise: ["cNoiseScale", "cColor", "cNoiseSphereEnable", "cNoiseGraphEnable"],
	Checker: ["cWidth", "cHeight"],
	FlameLance: ["cSize", "cSpeed", "cPower", "cAngle", "cColor", "cNoiseSize", "cNoiseStrength", "cNoiseDepth"],
	Bonfire: ["cSpeed", "cIntensity", "cStrength", "cDensity", "cSize", "cColor"],
	Snow: ["cSpeed", "cScale", "cDensity", "cRange"],
	DiamondGear: ["cScale", "cWidth", "cRadius", "cDiamondGearTeeth", "cDiamondGearMid"],
	BrushStroke: ["cWidth", "cStrength", "cAlpha", "cAngle", "cAmplitude", "cBrushStrokeX1", "cBrushStrokeY1", "cBrushStrokeX2", "cBrushStrokeY2", "cColor"],
	Speckle: ["cRadius", "cScale", "cDensity"],
	Bubbles: ["cRadius", "cWidth", "cThickness", "cColor", "cBubblesVariation"],
	Pentagon: ["cScale", "cAlpha", "cWidth"],
	Grunge: ["cRadius", "cScale"],
	Energy: ["cPower", "cDensity", "cThickness", "cScale", "cFrequency", "cColor"],
	InkSplat: ["cSplatLines", "cSplatSpotStep"],
	Particle: ["cSize", "cLifeTime", "cGravity", "cCount"],
	Electric: ["cFrequency", "cScale"],
	Caustics: ["cScale", "cSpeed", "cColor"],
	Squiggles: ["cSize", "cScale", "cDensity"],
	WaterTurbulence: ["cScale", "cIntensity"],
	Trabeculum: ["cDensity", "cScale", "cIntensity", "cTrabeculumVariation", "cCameraTilt", "cCameraPan", "cColor"],
	BinaryMatrix: [],
	Test: []
};

/**
 * Per-parameter GUI config: ranges, names, step sizes.
 */
export const PARAMETER_CONFIG = {
	cFrequency: { minValue: 0, maxValue: 50, name: "Frequency" },
	cPowerExponent: { minValue: 0, maxValue: 5, name: "PowerExponent" },
	cAmplitude: { minValue: 0, maxValue: 0.2, name: "Amplitude" },
	cIntensity: { minValue: 0, maxValue: 1, name: "Intensity", step: 0.01 },
	cDirectionX: { minValue: -1, maxValue: 1, name: "Direction X", step: 0.1 },
	cDirectionY: { minValue: -1, maxValue: 1, name: "Direction Y", step: 0.1 },
	cRadius: { minValue: 0, maxValue: 2, name: "Radius", step: 0.01 },
	cInnerRadius: { minValue: 0, maxValue: 2, name: "InnerRadius" },
	cInnerRadius2: { minValue: 0, maxValue: 2, name: "InnerRadius2" },
	cWidth: { minValue: 0, maxValue: 1, name: "Width", step: 0.01 },
	cHeight: { minValue: 0, maxValue: 1, name: "Height" },
	cDepth: { minValue: 0, maxValue: 1, name: "Depth" },
	cOffset: { minValue: 0, maxValue: 1, name: "Offset", step: 0.1 },
	cPetals: { minValue: 1, maxValue: 20, name: "Petals" },
	cVolume: { minValue: 1, maxValue: 10, name: "Volume" },
	cBeta: { minValue: 1, maxValue: 10, name: "Beta" },
	cDelta: { minValue: 0.01, maxValue: 0.2, name: "Delta" },
	cScale: { minValue: 0.1, maxValue: 1, name: "Scale" },
	cSize: { minValue: 0.1, maxValue: 5, name: "Size" },
	cColor: { minValue: 0, maxValue: 1, name: "Color", step: 0.1 },
	cInnerWidth: { minValue: 0, maxValue: 1, name: "Inner Width" },
	cStrength: { minValue: 0, maxValue: 5, name: "Strength" },
	cPower: { minValue: 0, maxValue: 1, name: "Power" },
	cRange: { minValue: 0, maxValue: 5, name: "Range" },
	cEmission: { minValue: 0, maxValue: 1, name: "Emission" },
	cBloom: { minValue: 0, maxValue: 1, name: "Bloom", step: 0.1 },
	cLightX: { minValue: -1, maxValue: 1, name: "Light X", step: 0.01 },
	cLightY: { minValue: -1, maxValue: 1, name: "Light Y", step: 0.01 },
	cLightZ: { minValue: -1, maxValue: 1, name: "Light Z", step: 0.01 },
	cAmbient: { minValue: 0, maxValue: 1, name: "Ambient" },
	cSmoothness: { minValue: 0, maxValue: 1, name: "Smoothness" },
	cSmoothnessPower: { minValue: 1, maxValue: 5, name: "Smoothness Power" },
	cThickness: { minValue: 0, maxValue: 1, name: "Thickness" },
	cThicknessPower: { minValue: 1, maxValue: 5, name: "Thickness Power" },
	cCameraTilt: { minValue: 0, maxValue: 1, name: "CameraTilt", step: 0.01 },
	cCameraPan: { minValue: 0, maxValue: 1, name: "CameraPan", step: 0.01 },
	cSpeed: { minValue: 0, maxValue: 10, name: "Speed" },
	cAngle: { minValue: 0, maxValue: 360, name: "Angle", step: 0.01 },
	cDensity: { minValue: 0, maxValue: 1, name: "Density", step: 0.01 },
	cAlpha: { minValue: 0, maxValue: 1, name: "Alpha", step: 0.01 },
	cDiamondGearTeeth: { minValue: 8, maxValue: 32, name: "Teeth", step: 1 },
	cDiamondGearMid: { minValue: 0, maxValue: 1, name: "Mid", step: 0.01 },
	cBrushStrokeX1: { minValue: -1, maxValue: 1, name: "X1", step: 0.01 },
	cBrushStrokeY1: { minValue: -1, maxValue: 1, name: "Y1", step: 0.01 },
	cBrushStrokeX2: { minValue: -1, maxValue: 1, name: "X2", step: 0.01 },
	cBrushStrokeY2: { minValue: -1, maxValue: 1, name: "Y2", step: 0.01 },
	cBubblesVariation: { minValue: 1, maxValue: 2, name: "Variation", step: 1 },
	cFlameEyeInnerFade: { minValue: 0.01, maxValue: 1, name: "InnerFade", step: 0.01 },
	cFlameEyeOuterFade: { minValue: 0.01, maxValue: 1, name: "OuterFade", step: 0.01 },
	cFlameEyeBorder: { minValue: 0.01, maxValue: 1, name: "Border", step: 0.01 },
	cSplatLines: { minValue: 1, maxValue: 100, name: "Lines" },
	cSplatSpotStep: { minValue: 0.02, maxValue: 0.1, name: "Spot Step", step: 0.02 },
	cTrabeculumVariation: { minValue: 0, maxValue: 2, name: "Variation", step: 1 },
	cLifeTime: { minValue: 0, maxValue: 1, name: "Life Time", step: 0.01 },
	cGravity: { minValue: 0, maxValue: 1, name: "Gravity", step: 0.01 },
	cCount: { minValue: 0, maxValue: 500, name: "Count", step: 1 },
	cExplosionRadius: { minValue: 1, maxValue: 2, name: "Radius" },
	cExplosionDownScale: { minValue: 1, maxValue: 2, name: "DownScale" },
	cExplosionGrain: { minValue: 1, maxValue: 5, name: "Grain" },
	cExplosionSpeed: { minValue: 0.1, maxValue: 2, name: "Speed" },
	cExplosionBallness: { minValue: 2, maxValue: 50, name: "Ballness" },
	cExplosionGrowth: { minValue: 0.1, maxValue: 3, name: "Growth" },
	cExplosionFade: { minValue: 1, maxValue: 5, name: "Fade" },
	cExplosionDensity: { minValue: 0.1, maxValue: 4, name: "Density" },
	cExplosionContrast: { minValue: 0.1, maxValue: 4, name: "Contrast" },
	cExplosionRollingInitDamp: { minValue: 0.1, maxValue: 2, name: "RollingInitDamp" },
	cExplosionRollingSpeed: { minValue: 0, maxValue: 4, name: "RollingSpeed" },
	cExplosionDelayRange: { minValue: 0.1, maxValue: 2, name: "DelayRange" },
	cExplosionBallSpread: { minValue: 0.1, maxValue: 5, name: "BallSpread" },
	cNoiseOctave: { minValue: 1, maxValue: 8, name: "NoiseOctave" },
	cNoiseFrequency: { minValue: 0, maxValue: 2, name: "NoiseFrequency", step: 0.01 },
	cNoisePersistence: { minValue: 0, maxValue: 1, name: "NoisePersistence" },
	cNoiseAmplitude: { minValue: 0, maxValue: 1, name: "NoiseAmplitude", step: 0.01 },
	cNoiseScale: { minValue: 0, maxValue: 1, name: "NoiseScale" },
	cNoiseSphereEnable: { name: "NoiseSphere" },
	cNoiseGraphEnable: { name: "NoiseGraph" },
	cNoiseSize: { minValue: 0.1, maxValue: 10, name: "NoiseSize" },
	cNoiseStrength: { minValue: 0.1, maxValue: 1, name: "NoiseStrength" },
	cNoiseDepth: { minValue: 1, maxValue: 5, name: "NoiseDepth" },
	cNoiseLacunarity: { minValue: 1, maxValue: 4, step: 1, name: "NoiseLacunarity" },
	cRepeat: { minValue: 1, maxValue: 8, step: 1, name: "Repeat" },
	cScaleShift: { minValue: 0, maxValue: 1, name: "ScaleShift" },
	cBias: { minValue: -1, maxValue: 1, name: "Bias" },
	cGain: { minValue: -1, maxValue: 1, name: "Gain" },
	cInvert: { minValue: 0, maxValue: 1, name: "Invert" },
	cThreshold: { minValue: 0, maxValue: 1, name: "Threshold" },
	cTurbulence: { minValue: 0, maxValue: 1, name: "Turbulence" },
	cRidge: { minValue: 0, maxValue: 1, name: "Ridge" },
	cRidgeOffset: { minValue: 0, maxValue: 1, name: "RidgeOffset" },
	cGradientNoise: { minValue: 0, maxValue: 1, name: "GradientNoise" },
	cValueNoise: { minValue: 0, maxValue: 1, name: "ValueNoise" },
	cVoronoiNoise: { minValue: 0, maxValue: 1, name: "VoronoiNoise" },
	cVoronoiCell: { minValue: 0, maxValue: 1, name: "VoronoiCell" },
	cSimplexNoise: { minValue: 0, maxValue: 1, name: "SimplexNoise" }
};

/**
 * Per-type parameter overrides (non-default ranges or default values).
 */
export const PARAMETER_OVERRIDES = {
	Circle: { cPowerExponent: { minValue: 0, maxValue: 50 } },
	Gradation: { cPowerExponent: { minValue: 0, maxValue: 50 } },
	GradationLine: { cPowerExponent: { minValue: 0, maxValue: 50 } },
	Cone: { cPowerExponent: { minValue: 0, maxValue: 50 } },
	Cell: { cPowerExponent: { minValue: 0, maxValue: 50 } },
	Flame: { cWidth: { minValue: 0.1, maxValue: 2 } },
	Lightning: { cFrequency: { minValue: 0, maxValue: 2 }, cWidth: { minValue: 1, maxValue: 10 } },
	Cloud: { cCameraPan: { minValue: 0, maxValue: 1, defaultValue: 0 }, cCameraTilt: { minValue: 0, maxValue: 1, defaultValue: 0 } },
	Checker: { cWidth: { minValue: 1, maxValue: 100 }, cHeight: { minValue: 1, maxValue: 100 } },
	CoherentNoise: { cPowerExponent: { minValue: 0, maxValue: 5, defaultValue: 1 }, cNoiseOctave: { minValue: 1, maxValue: 6, step: 1, defaultValue: 6 }, cNoiseFrequency: { minValue: 1, maxValue: 32, step: 1, defaultValue: 4 }, cNoiseAmplitude: { minValue: 0, maxValue: 2, defaultValue: 1 }, cNoisePersistence: { minValue: 0, maxValue: 1, defaultValue: 0.5 } },
	FbmNoise2: { cNoiseOctave: { minValue: 1, maxValue: 3, defaultValue: 3 }, cNoiseAmplitude: { minValue: 0, maxValue: 0.5, defaultValue: 0.25 }, cNoiseFrequency: { minValue: 0, maxValue: 1, defaultValue: 1 } },
	FbmNoise3: { cNoiseOctave: { minValue: 1, maxValue: 8, defaultValue: 5 }, cNoiseAmplitude: { minValue: 0.5, maxValue: 1.5, defaultValue: 1 }, cNoiseFrequency: { minValue: 0, maxValue: 2, defaultValue: 0.5 }, cNoiseScale: { minValue: 0.01, maxValue: 1 } },
	MarbleNoise: { cScale: { minValue: 1, maxValue: 100 }, cFrequency: { minValue: 1, maxValue: 100 } },
	TessNoise: { cNoiseFrequency: { minValue: 0, maxValue: 1, defaultValue: 0.1 } },
	FlameEye: { cSpeed: { minValue: 0.1, maxValue: 1 } },
	FlameLance: { cSize: { minValue: 1, maxValue: 100 }, cSpeed: { minValue: 0.1, maxValue: 5 }, cPower: { minValue: 0.1, maxValue: 10 }, cAngle: { minValue: -1, maxValue: 1 } },
	Bonfire: { cSpeed: { minValue: 0.1, maxValue: 1 }, cIntensity: { minValue: 0.1, maxValue: 5 }, cStrength: { minValue: 0.1, maxValue: 1 }, cDensity: { minValue: 0.1, maxValue: 4 }, cSize: { minValue: 0, maxValue: 10 } },
	Snow: { cDensity: { minValue: 0.1, maxValue: 6 }, cRange: { minValue: 0.1, maxValue: 1 } },
	DiamondGear: { cWidth: { minValue: 0.1, maxValue: 8 } },
	BrushStroke: { cWidth: { minValue: 0, maxValue: 1, defaultValue: 0.3 }, cAlpha: { minValue: 0, maxValue: 1, defaultValue: 0.58 }, cStrength: { minValue: 0.1, maxValue: 1, defaultValue: 0.6 }, cAngle: { minValue: 0, maxValue: 1 }, cAmplitude: { minValue: 0, maxValue: 1 } },
	Speckle: { cRadius: { minValue: 0.01, maxValue: 1, defaultValue: 1 }, cDensity: { minValue: 0.01, maxValue: 1, defaultValue: 0.1 }, cScale: { minValue: 0.01, maxValue: 1, defaultValue: 0.01 } },
	Pentagon: { cWidth: { minValue: 0.01, maxValue: 1, defaultValue: 0.02 }, cScale: { minValue: 0.01, maxValue: 1, defaultValue: 0.5 }, cAlpha: { minValue: 0.01, maxValue: 1, defaultValue: 0.38 } },
	Grunge: { cRadius: { minValue: 0.01, maxValue: 1 } },
	Energy: { cPower: { minValue: 0, maxValue: 1 }, cFrequency: { minValue: 0, maxValue: 1 } },
	Particle: { cSize: { minValue: 0.01, maxValue: 0.5 } },
	Electric: { cFrequency: { minValue: 10, maxValue: 50 }, cScale: { minValue: 0.01, maxValue: 1 } },
	Caustics: { cScale: { minValue: 1, maxValue: 10 }, cSpeed: { minValue: 1, maxValue: 4 } },
	Squiggles: { cSize: { minValue: 1, maxValue: 8 }, cScale: { minValue: 0.01, maxValue: 1, defaultValue: 0.5 }, cDensity: { minValue: 1, maxValue: 16 } },
	WaterTurbulence: { cSize: { minValue: 0.01, maxValue: 1, defaultValue: 0.4 }, cIntensity: { minValue: 0.01, maxValue: 1, defaultValue: 0.15 } },
	Trabeculum: { cDensity: { minValue: 0, maxValue: 1, defaultValue: 1 }, cScale: { minValue: 0.01, maxValue: 1, defaultValue: 1 }, cCameraPan: { minValue: 0, maxValue: 1, defaultValue: 0.5 }, cCameraTilt: { minValue: 0, maxValue: 1, defaultValue: 0.5 } }
};
